create table pageviews (
  id bigint generated by default as identity primary key,
  slug varchar not null unique,
  view_count bigint default 1,
  inserted_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

comment
  on table public.pageviews is 'Page views for each page.';

CREATE OR REPLACE FUNCTION update_views(page_slug TEXT)
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
  IF EXISTS (SELECT FROM pageviews WHERE slug=page_slug) THEN
    UPDATE pageviews
    SET view_count = view_count + 1,
      updated_at = now()
    WHERE slug = page_slug;
  ELSE
    INSERT into pageviews(slug) VALUES (page_slug);
  END IF;
END;
$$;

alter publication
  supabase_realtime
add
  table public.pageviews;